import React from 'react';
import { Sprout, ShieldAlert, Heart } from 'lucide-react';

export default function Footer() {
  return (
    <footer className="border-t border-slate-800/80 bg-slate-950/60 mt-20 text-slate-400 text-sm">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
          <div className="md:col-span-2 space-y-4">
            <div className="flex items-center space-x-2">
              <Sprout className="w-6 h-6 text-emerald-400" />
              <span className="text-lg font-bold text-white">SmartCrop AI</span>
            </div>
            <p className="text-slate-400 text-xs leading-relaxed max-w-md">
              An intelligent agricultural decision-support platform leveraging transfer learning computer vision, XGBoost yield regression, multi-factor crop risk calibration, and Explainable AI (Grad-CAM & SHAP).
            </p>
            <div className="flex items-center space-x-2 text-xs text-amber-400/90 bg-amber-950/30 border border-amber-500/20 p-3 rounded-lg">
              <ShieldAlert className="w-5 h-5 flex-shrink-0" />
              <span>
                <strong>Disclaimer:</strong> Predictions generated by SmartCrop AI are decision-support estimates and should be verified with local agricultural extension experts.
              </span>
            </div>
          </div>

          <div>
            <h4 className="text-white font-semibold text-sm mb-3">ML Pipelines</h4>
            <ul className="space-y-2 text-xs">
              <li>EfficientNet-B0 / MobileNetV2 Disease Classifier</li>
              <li>XGBoost Crop Yield Regressor</li>
              <li>Multi-Factor Risk Classifier</li>
              <li>Grad-CAM Visual Heatmaps</li>
              <li>SHAP Tabular Explainability</li>
            </ul>
          </div>

          <div>
            <h4 className="text-white font-semibold text-sm mb-3">Resources</h4>
            <ul className="space-y-2 text-xs">
              <li>REST API Documentation (/docs)</li>
              <li>PlantVillage Dataset Standard</li>
              <li>FAO Good Agricultural Practices</li>
              <li>What-If Scenario Simulator</li>
            </ul>
          </div>
        </div>

        <div className="border-t border-slate-800/60 mt-10 pt-6 flex flex-col sm:flex-row justify-between items-center text-xs text-slate-500">
          <p>© {new Date().getFullYear()} SmartCrop AI Platform. Built for Agronomic Research & Placements.</p>
          <p className="flex items-center space-x-1 mt-2 sm:mt-0">
            <span>Powered by PyTorch & XGBoost</span>
          </p>
        </div>
      </div>
    </footer>
  );
}
